name: flexible_expansion_list
description: A Flutter widget provide expansion lists in a flexible way.
version: 0.0.2
repository: https://github.com/horam/flexible-expansion-list

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0